### ISSUE TITLE
Node Version Compatibility

### ISSUE THREAD

**Issue by Bk8** [scottstensland/websockets-streaming-audio#7]
I'm  trying to run this on Node 10.16.0 on Mac, but it is not working anymore. With what version of Node was this project built?

**Comment by pahund** [comment]
Quoting Scott from another issue:

> node 0.10.x ... it works using that version ... its what packages.json says and what demo uses

I can confirm that the streams work with Node.js version 0.10.48. With the latest version 10, I get no sound, only some noise when I click on the "stream 17" button

**Comment by scottstensland** [comment]
try now ... two independent issues are now fixed

1)    all browsers put a breaking change to shut off autoPlay which impacted how Web Audio API audio context gets maintained ... its fixed now

2)   I bumped up all upstream dependancies to their current releases, and fixed a `new Buffer()` message

So its working OK now using nodejs 12.14.0   --- enjoy,
